version: '2'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: app
    networks:
      - myapp-network
    depends_on:
      - db

  db:
    image: mysql:8
    networks:
      - myapp-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=schoolDb
    ports:
      - "3306:3306"
networks:
  myapp-network: